language: rust

rust:
  - stable
  - beta

matrix:
  fast_finish: true
  allow_failures:
    - rust: beta

before_script:
  - rustup component add clippy
  - rustup component add rustfmt

script:
  - cargo check
  - cargo clippy
  - cargo fmt --all -- --check
  - cargo test
