[package]
name = "todo"
version = "0.1.0"
authors = ["Nathan Knowler <nathan@knowler.me>"]
edition = "2018"

[dependencies]
dirs = "1.0"
structopt = "0.2.14"
toml = "0.4.10"
chrono = "0.4.11"
serde = "1.0.88"
serde_derive = "1.0.88"
